spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/notify_rail?serverTimezone=Asia/Seoul
    username: notify
    password: notify

  rabbitmq:
    host: localhost
    port: 5672
    username: notify
    password: notify

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

notify:
  queue:
    type: rabbitmq
  rabbitmq:
    delivery-exchange: notify.delivery.exchange
    delivery-queue: notify.delivery.queue
    delivery-routing-key: delivery.requested