spring:
  application:
    name: notify-rail-worker

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  http:
    clients:
      connect-timeout: 3s
      read-timeout: 5s
      redirects: dont_follow

notify:
  worker:
    delivery:
      max-concurrency: 10